# Generated by Django 4.0.4 on 2022-05-11 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('table_title', models.CharField(max_length=120, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('date_aired', models.DateField(blank=True)),
                ('status', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=150)),
                ('genre', models.ManyToManyField(to='anime.animecategory')),
            ],
        ),
    ]
